# See a list of the default styles at:
#
#  https://github.com/bbatsov/rubocop/blob/master/config/default.yml

inherit_from: .rubocop_todo.yml

AllCops:
  Include:
    - rubocop-rspec
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - spec/support/auth0_support.rb

# Include: **/Gemfile, **/gems.rb
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Documentation:
  Exclude:
    - app/models/application_record.rb
    - app/helpers/*
    - app/mailers/*
    - spec/**
    - spec/**/**

Metrics/BlockLength:
  ExcludedMethods:
    - configure

# Extend the maximum line length to 120 characters.
Metrics/LineLength:
  Max: 120

Security/MarshalLoad:
  Exclude:
    - lib/tasks/sessions.rake

# Allow block comments to be used.
# =begin
#   :commented_out_block
# =end
Style/BlockComments:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: true

# Allow more than one blank line
Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Style/ExtraSpacing:
  Enabled: false

# Allow { :this } and [ :this ]
Style/SpaceInsideBrackets:
  Enabled: false
