# See a list of the default styles at:
#
#  https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  TargetRubyVersion: 2.4
  Include:
    - rubocop-rspec
    - '**/Gemfile'
    - '**/Rakefile'
  Exclude:
    - spec/support/auth0_support.rb
    - vendor/**/*
    - db/migrate/**

# Include: **/Gemfile, **/gems.rb
Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'

Documentation:
  Exclude:
    - app/models/application_record.rb
    - app/helpers/*
    - app/mailers/*
    - spec/**
    - spec/**/**

MethodLength:
  Max: 15

# The ABC size is a calculated magnitude, so this number can be an Integer or a Float.
Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  ExcludedMethods:
    - configure
    - context
    - describe

# Extend the maximum line length to 120 characters.
Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/**
    - spec/**/**

Security/MarshalLoad:
  Exclude:
    - lib/tasks/sessions.rake

# Allow block comments to be used.
# =begin
#   :commented_out_block
# =end
Style/BlockComments:
  Enabled: false

Style/ExtraSpacing:
  AllowForAlignment: true

# Allow more than one blank line
Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Style/ExtraSpacing:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Allow { :this } and [ :this ]
Style/SpaceInsideBrackets:
  Enabled: false
